### ISSUE TITLE
مشكل المفتاح

### ISSUE THREAD

**Issue by gharibelatoir** [prjkt-nv404/UDP-Custom-Installer-Manager#1]
Key problem I entered the telegram bot and did not find the key where it is

**Comment by iykex** [comment]
_There's no Telegram bot attached to tool._

**Comment by gharibelatoir** [comment]
And how do I get the private key for the udp custom script

**Comment by iykex** [comment]
If i understand, you wanted to get a verification/installation key.
If it's so, then communicate it through the bot: [click here 🤖 ](https://t.me/voltverifybot)

**Comment by gharibelatoir** [comment]
The key does not exist. Do you understand that it does not exist?

**Comment by gharibelatoir** [comment]
I clicked on the link you sent me and it still doesn't have the key

**Comment by iykex** [comment]
Tell the bot you're from GitHub.
All the best.

**Comment by litucks** [comment]
Just grab one of these keys:

```
"fzL2k24xyz",
"BraQmexVlt",
"BrDaPEMx15",
"4Hillary05",
"KingAsdu00",
"Rasel007xy",
"isaacantwi",
"VltX007SBi",
"DoniXyZiA7",
"Vf15UGetXy",
"SheGn07xYz",
"HillarY010",
"StYawexY07",
"HasiLm07Xy",
"el7onXyZie",
"cH4rwn7xYz",
"2mViSioN8a",
"Blake007Ug",
"MoAvltx90i",
"ricky007xi",
"viSpro13mx"
```
